SET NOCOUNT ON
GO
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp fin', 47, 'Accounting')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man tech tran', 94, 'Airlines/Aviation')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('leg org', 120, 'Alternative Dispute Resolution')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 125, 'Alternative Medicine')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med', 127, 'Animation')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 19, 'Apparel &amp; Fashion')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons', 50, 'Architecture &amp; Planning')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 111, 'Arts and Crafts')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 53, 'Automotive')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov man', 52, 'Aviation &amp; Aerospace')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 41, 'Banking')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov hlth tech', 12, 'Biotechnology')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 36, 'Broadcast Media')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons', 49, 'Building Materials')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp man', 138, 'Business Supplies and Equipment')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 129, 'Capital Markets')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 54, 'Chemicals')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org serv', 90, 'Civic &amp; Social Organization')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons gov', 51, 'Civil Engineering')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons corp fin', 128, 'Commercial Real Estate')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 118, 'Computer &amp; Network Security')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 109, 'Computer Games')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 3, 'Computer Hardware')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 5, 'Computer Networking')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 4, 'Computer Software')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons', 48, 'Construction')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 24, 'Consumer Electronics')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 25, 'Consumer Goods')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org serv', 91, 'Consumer Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 18, 'Cosmetics')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('agr', 65, 'Dairy')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov tech', 1, 'Defense &amp; Space')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med', 99, 'Design')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('edu', 69, 'Education Management')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('edu org', 132, 'E-Learning')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 112, 'Electrical/Electronic Manufacturing')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 28, 'Entertainment')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org serv', 86, 'Environmental Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp rec serv', 110, 'Events Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 76, 'Executive Office')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp serv', 122, 'Facilities Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('agr', 63, 'Farming')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 43, 'Financial Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 38, 'Fine Art')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('agr', 66, 'Fishery')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec serv', 34, 'Food &amp; Beverages')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man serv', 23, 'Food Production')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org', 101, 'Fund-Raising')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 26, 'Furniture')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec', 29, 'Gambling &amp; Casinos')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons man', 145, 'Glass, Ceramics &amp; Concrete')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 75, 'Government Administration')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 148, 'Government Relations')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med', 140, 'Graphic Design')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth rec', 124, 'Health, Wellness and Fitness')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('edu', 68, 'Higher Education')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 14, 'Hospital &amp; Health Care')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec serv tran', 31, 'Hospitality')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 137, 'Human Resources')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp good tran', 134, 'Import and Export')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org serv', 88, 'Individual &amp; Family Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons man', 147, 'Industrial Automation')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med serv', 84, 'Information Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech" selected="', 96, 'Information Technology and Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 42, 'Insurance')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 74, 'International Affairs')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov org tran', 141, 'International Trade and Development')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 6, 'Internet')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 45, 'Investment Banking')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin', 46, 'Investment Management')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov leg', 73, 'Judiciary')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov leg', 77, 'Law Enforcement')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('leg', 9, 'Law Practice')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('leg', 10, 'Legal Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov leg', 72, 'Legislative Office')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec serv tran', 30, 'Leisure, Travel &amp; Tourism')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec serv', 85, 'Libraries')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp tran', 116, 'Logistics and Supply Chain')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 143, 'Luxury Goods &amp; Jewelry')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 55, 'Machinery')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 11, 'Management Consulting')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tran', 95, 'Maritime')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp med', 80, 'Marketing and Advertising')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 97, 'Market Research')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons gov man', 135, 'Mechanical or Industrial Engineering')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 126, 'Media Production')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 17, 'Medical Devices')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 13, 'Medical Practice')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 139, 'Mental Health Care')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 71, 'Military')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 56, 'Mining &amp; Metals')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 35, 'Motion Pictures and Film')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 37, 'Museums and Institutions')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art rec', 115, 'Music')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov man tech', 114, 'Nanotechnology')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 81, 'Newspapers')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org', 100, 'Nonprofit Organization Management')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 57, 'Oil &amp; Energy')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med', 113, 'Online Media')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 123, 'Outsourcing/Offshoring')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('serv tran', 87, 'Package/Freight Delivery')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 146, 'Packaging and Containers')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 61, 'Paper &amp; Forest Products')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 39, 'Performing Arts')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth tech', 15, 'Pharmaceuticals')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org', 131, 'Philanthropy')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 136, 'Photography')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 117, 'Plastics')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov org', 107, 'Political Organization')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('edu', 67, 'Primary/Secondary Education')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 83, 'Printing')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 105, 'Professional Training &amp; Coaching')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp org', 102, 'Program Development')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 79, 'Public Policy')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 98, 'Public Relations and Communications')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov', 78, 'Public Safety')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('med rec', 82, 'Publishing')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 62, 'Railroad Manufacture')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('agr', 64, 'Ranching')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('cons fin good', 44, 'Real Estate')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec serv', 40, 'Recreational Facilities and Services')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('org serv', 89, 'Religious Institutions')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov man org', 144, 'Renewables &amp; Environment')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('edu gov', 70, 'Research')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec serv', 32, 'Restaurants')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man', 27, 'Retail')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp org serv', 121, 'Security and Investigations')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 7, 'Semiconductors')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 58, 'Shipbuilding')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good rec', 20, 'Sporting Goods')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('rec', 33, 'Sports')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp', 104, 'Staffing and Recruiting')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 22, 'Supermarkets')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov tech', 8, 'Telecommunications')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 60, 'Textiles')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('gov org', 130, 'Think Tanks')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 21, 'Tobacco')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('corp gov serv', 108, 'Translation and Localization')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tran', 92, 'Transportation/Trucking/Railroad')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('man', 59, 'Utilities')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('fin tech', 106, 'Venture Capital &amp; Private Equity')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('hlth', 16, 'Veterinary')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tran', 93, 'Warehousing')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good', 133, 'Wholesale')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('good man rec', 142, 'Wine and Spirits')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('tech', 119, 'Wireless')
INSERT INTO [dbo].[Industry] ([Tags], [Id], [Name]) VALUES ('art med rec', 103, 'Writing and Editing')
GO