SET NOCOUNT ON
GO
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AD','Andorra')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AF','Afghanistan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AG','Antigua and Barbuda')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AI','Anguilla')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AL','Albania')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AM','Armenia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AN','Netherlands Antilles')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AO','Angola')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AR','Argentina')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AS','American Samoa')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AT','Austria')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AU','Australia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AW','Aruba')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('AZ','Azerbaijan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BA','Bosnia and Herzegovina')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BB','Barbados')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BD','Bangladesh')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BE','Belgium')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BF','Burkina Faso')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BG','Bulgaria')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BH','Bahrain')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BI','Burundi')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BJ','Benin')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BM','Bermuda')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BN','Brunei Darussalam')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BO','Bolivia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BR','Brazil')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BS','Bahamas')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BT','Bhutan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BW','Botswana')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BY','Belarus')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('BZ','Belize')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CA','Canada')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CD','Congo, The Democratic Republic of the')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CF','Central African Republic')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CG','Congo')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CH','Switzerland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CI','Cote d''Ivoire')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CK','Cook Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CL','Chile')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CM','Cameroon')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CN','China')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CO','Colombia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CR','Costa Rica')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CU','Cuba')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CV','Cape Verde')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CX','Christmas Island')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CY','Cyprus')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('CZ','Czech Republic')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DE','Germany')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DJ','Djibouti')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DK','Denmark')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DM','Dominica')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DO','Dominican Republic')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('DZ','Algeria')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('EC','Ecuador')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('EE','Estonia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('EG','Egypt')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ER','Eritrea')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ES','Spain')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ET','Ethiopia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FI','Finland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FJ','Fiji')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FK','Falkland Islands (Malvinas)')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FM','Micronesia, Federated States of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FO','Faroe Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('FR','France')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GA','Gabon')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GD','Grenada')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GE','Georgia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GF','French Guiana')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GG','Guernsey')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GH','Ghana')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GI','Gibraltar')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GL','Greenland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GM','Gambia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GN','Guinea')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GP','Guadeloupe')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GQ','Equatorial Guinea')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GR','Greece')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GS','South Georgia and the South Sandwich Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GT','Guatemala')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GU','Guam')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GW','Guinea-Bissau')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('GY','Guyana')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('HK','Hong Kong')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('HN','Honduras')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('HR','Croatia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('HT','Haiti')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('HU','Hungary')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ID','Indonesia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IE','Ireland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IL','Israel')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IM','Isle of Man')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IN','India')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IQ','Iraq')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IR','Iran, Islamic Republic of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IS','Iceland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('IT','Italy')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('JE','Jersey')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('JM','Jamaica')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('JO','Jordan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('JP','Japan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KE','Kenya')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KG','Kyrgyzstan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KH','Cambodia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KI','Kiribati')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KM','Comoros')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KN','Saint Kitts and Nevis')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KP','Korea, Democratic People''s Republic of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KR','Korea, Republic of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KW','Kuwait')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KY','Cayman Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('KZ','Kazakhstan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LA','Lao People''s Democratic Republic')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LB','Lebanon')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LC','Saint Lucia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LI','Liechtenstein')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LK','Sri Lanka')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LR','Liberia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LS','Lesotho')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LT','Lithuania')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LU','Luxembourg')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LV','Latvia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('LY','Libyan Arab Jamahiriya')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MA','Morocco')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MC','Monaco')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MD','Moldova, Republic of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ME','Montenegro')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MG','Madagascar')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MH','Marshall Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MK','Macedonia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ML','Mali')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MM','Myanmar')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MN','Mongolia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MO','Macao')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MQ','Martinique')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MR','Mauritania')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MS','Montserrat')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MT','Malta')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MU','Mauritius')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MV','Maldives')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MW','Malawi')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MX','Mexico')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MY','Malaysia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('MZ','Mozambique')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NA','Namibia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NC','New Caledonia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NE','Niger')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NF','Norfolk Island')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NG','Nigeria')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NI','Nicaragua')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NL','Netherlands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NO','Norway')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NP','Nepal')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NU','Niue')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('NZ','New Zealand')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('OM','Oman')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PA','Panama')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PE','Peru')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PF','French Polynesia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PG','Papua New Guinea')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PH','Philippines')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PK','Pakistan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PL','Poland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PM','Saint Pierre and Miquelon')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PN','Pitcairn')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PR','Puerto Rico')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PS','Palestinian Territory')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PT','Portugal')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PW','Palau')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('PY','Paraguay')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('QA','Qatar')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('RE','Reunion')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('RO','Romania')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('RS','Serbia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('RU','Russian Federation')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('RW','Rwanda')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SA','Saudi Arabia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SB','Solomon Islands')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SC','Seychelles')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SD','Sudan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SE','Sweden')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SG','Singapore')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SH','Saint Helena')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SI','Slovenia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SJ','Svalbard and Jan Mayen')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SK','Slovakia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SL','Sierra Leone')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SM','San Marino')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SN','Senegal')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SO','Somalia')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SR','Suriname')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ST','Sao Tome and Principe')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SV','El Salvador')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SY','Syrian Arab Republic')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('SZ','Swaziland')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('TD','Chad')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('TH','Thailand')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('TJ','Tajikistan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('TW','Taiwan')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('TZ','Tanzania, United Republic of')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('VA','Holy See (Vatican City State)')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('VC','Saint Vincent and the Grenadines')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('WS','Samoa')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('YT','Mayotte')
INSERT INTO [dbo].[Country] ([Code], [Name])VALUES ('ZA','South Africa')
